name: Go Compiler

on:
  push:
    branches: [ main ]
    paths-ignore: 
      - LICENSE
      - README.md
  pull_request:
    branches: [ main ]
    paths-ignore: 
      - LICENSE
      - README.md

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.15.5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      -
        name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: ${{ matrix.go_version }}
          dest: bin
          prefix: dsvha
          targets: windows/386,windows/amd64,linux/386,linux/amd64,darwin/386,darwin/amd64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
      -
        name: Upload production to Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Binary
          path: bin
